---
- name: Create curator etc dir
  file:
    path: "{{ elastic_curator_etc_dir }}{{ item }}"
    state: directory
  with_items:
    - "/"
    - "/actions"

- name: Copy curator config
  copy:
    content: "{{ elastic_curator_config_yaml | to_nice_yaml }}"
    dest: "{{ elastic_curator_etc_dir }}/curator.yml"
    mode: "0644"
    owner: root
    group: root

- name: Copy curator action file(s)
  copy:
    content: "{{ elastic_curator_actions[item.key] | to_nice_yaml }}"
    dest: "{{ elastic_curator_act_dir }}/{{ item.key }}.yml"
    mode: "0644"
    owner: root
    group: root
    validate: "{{elastic_curator_bin}} --config {{elastic_curator_etc_dir}}/curator.yml %s"
  with_dict: "{{ elastic_curator_actions }}"
